services:
  traefik:
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=hello@fluxend.app"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  fluxend_api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fluxend_api.rule=Host(`${API_SUB_DOMAIN}.${BASE_DOMAIN}`)"
      - "traefik.http.routers.fluxend_api.entrypoints=websecure"
      - "traefik.http.services.fluxend_api.loadbalancer.server.port=8080"
      - "traefik.http.routers.fluxend_api.tls=true"
      - "traefik.http.routers.fluxend_api.tls.certresolver=le"

  fluxend_frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fluxend_frontend.rule=Host(`${CONSOLE_SUB_DOMAIN}.${BASE_DOMAIN}`)"
      - "traefik.http.routers.fluxend_frontend.entrypoints=websecure"
      - "traefik.http.services.fluxend_frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.fluxend_frontend.tls=true"
      - "traefik.http.routers.fluxend_frontend.tls.certresolver=le"