SET ROLE fluxend;

GRANT USAGE ON SCHEMA public TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO web_anon;

CREATE ROLE {{USER_ROLE}} NOINHERIT;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{USER_ROLE}};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{USER_ROLE}};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO {{USER_ROLE}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO {{USER_ROLE}};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO {{USER_ROLE}};

GRANT web_anon TO {{USER_ROLE}};
GRANT {{USER_ROLE}} TO authenticator;