SET ROLE fluxton;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT USAGE ON SCHEMA public TO web_anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon; -- future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO web_anon; -- future functions
