name: Build and Deploy
on:
  push:
    branches: [ "main" ] # Only deploy on main branch pushes
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ] # Build and test on PRs to main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'LICENSE'

env:
  REGISTRY: docker.io
  API_IMAGE_NAME: fluxend/api
  FRONTEND_IMAGE_NAME: fluxend/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.title=${{ env.API_IMAGE_NAME }}
            org.opencontainers.image.description=Fluxend API Backend
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.title=${{ env.FRONTEND_IMAGE_NAME }}
            org.opencontainers.image.description=Fluxend Frontend
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          build-args: |
            VITE_FLX_INTERNAL_URL=${{ secrets.VITE_FLX_INTERNAL_URL }}
            VITE_FLX_API_URL=${{ secrets.VITE_FLX_API_URL }}
            VITE_FLX_BASE_DOMAIN=${{ secrets.VITE_FLX_BASE_DOMAIN }}
            VITE_FLX_HTTP_SCHEME=${{ secrets.VITE_FLX_HTTP_SCHEME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "\
            cd ${{ secrets.REMOTE_PATH }} && \
            docker compose pull && \
            make build"

      - name: Deployment complete
        run: echo "✅ Deployment complete to ${{ secrets.REMOTE_HOST }}"