name: Deploy Fluxend Application

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o bin/fluxend cmd/main.go

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Upload binary
          scp bin/fluxend ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
          
          # Restart container
          # TODO: Frontend should also be built and deployed
          ssh -t ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
          "cd /var/www/html/fluxend && \
           git pull && \
           make pgr.destroy && \
           make build && \
           docker-compose exec -T fluxend_api ./bin/fluxend udb.restart" 

      - name: Deployment complete
        run: echo "✅ Deployment complete to ${{ secrets.REMOTE_HOST }}"