name: Build Multi-platform Images
on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tag:
        description: 'Tag for the images'
        required: true
        default: 'multiplatform'

env:
  REGISTRY: docker.io
  API_IMAGE_NAME: fluxend/api
  FRONTEND_IMAGE_NAME: fluxend/frontend

jobs:
  build-multiplatform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # Both platforms for local dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.event.inputs.tag }}
            ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest-multiplatform
          cache-from: type=gha,scope=api-multiplatform
          cache-to: type=gha,mode=max,scope=api-multiplatform

      - name: Build and push multi-platform Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64  # Both platforms for local dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.event.inputs.tag }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest-multiplatform
          build-args: |
            VITE_FLX_INTERNAL_URL=${{ secrets.VITE_FLX_INTERNAL_URL }}
            VITE_FLX_API_URL=${{ secrets.VITE_FLX_API_URL }}
            VITE_FLX_BASE_DOMAIN=${{ secrets.VITE_FLX_BASE_DOMAIN }}
            VITE_FLX_HTTP_SCHEME=${{ secrets.VITE_FLX_HTTP_SCHEME }}
          cache-from: type=gha,scope=frontend-multiplatform
          cache-to: type=gha,mode=max,scope=frontend-multiplatform